import Navigation from '../../../components/Navigation/Navigation';

import '../globals.css'
import PageContainer from '../../../components/PageContainer/PageContainer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function SignUpLayout({ children }) {
  return (
    <>
      <Navigation withoutAnimation />
      <PageContainer>
        {children}
      </PageContainer>
    </>

  )
}
